on:
  fork:
    branches:
      - main
  push:
    branches:
    - main

jobs:
  macos-ssh-tunnel:
    name: masOS M1
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
          
